### ISSUE TITLE
Geocoder autocomplete behind map

### ISSUE THREAD

**Issue by mbtomlinson** [Open-Seat-Philly/open-seat#6]
The autocomplete box is overlapped by the map.  Can't figure out a fix

**Comment by rzane** [comment]
You'll want to set the [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index?v=example) of the dropdown to a number higher than the z-index of the map.

here's some pseudocode:

```css
.the-class-name-for-the-map {
  z-index: 1;
}

.the-class-name-for-the-dropdown {
  z-index: 2;
}
```
